name: GitHub Pages

on:
  push:
    branches:
    - master
jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      if: success()
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
      with:
        dir: docs
        branch: gh-pages
        token: ${{ secrets.ACCESS_TOKEN }}

